language: objective-c
osx_image: xcode9
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - PROJECT=CRDCoreDataStack.xcodeproj
  - IOS_SCHEME="CRDCoreDataStack"
  - IOS_SDK=iphonesimulator11.0
  - OSX_SCHEME="CRDCoreDataStackMac"
  - OSX_SDK=macosx10.13
  - WATCHOS_SCHEME="CRDCoreDataStackWatch"
  - WATCHOS_SDK=watchsimulator4.0
  - TVOS_SCHEME="CRDCoreDataStackTV"
  - TVOS_SDK=appletvsimulator11.0
  matrix:
    - DESTINATION="name=iPhone X" SCHEME="$IOS_SCHEME" SDK="$IOS_SDK" RUN_TESTS="NO" POD_LINT="NO"
    - DESTINATION="name=Apple Watch Series 3 - 42mm" SCHEME="$WATCHOS_SCHEME" SDK="$WATCHOS_SDK" RUN_TESTS="NO" POD_LINT="NO"
    - DESTINATION="name=Apple TV 1080p" SCHEME="$TVOS_SCHEME" SDK="$TVOS_SDK" RUN_TESTS="NO" POD_LINT="NO"
    - DESTINATION="arch=x86_64" SCHEME="$OSX_SCHEME" SDK="$OSX_SDK" RUN_TESTS="NO" POD_LINT="NO"

script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks

  # Build Framework in Debug and Run Tests if specified
  - if [ "$RUN_TESTS" == "YES" ]; then xcodebuild -project "$PROJECT" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO test; else xcodebuild -project "$PROJECT" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO build; fi

  # Run pod lib lint if specified
  - if [ "$POD_LINT" == "YES" ]; then pod lib lint --private --verbose; fi
